### ISSUE TITLE
[Building] create build process for "web" platform

### ISSUE THREAD

**Issue by andrepadez** [vigour-io/wrapper#123]
although this is called "vigour-native" i think it makes sense to be able to run `npm run web` like we do with `npm run android` or `npm run ios`

**Comment by shawninder** [comment]
yes, also, I intend to rename it to vigour-wrapper

**Comment by shawninder** [comment]
This is mostly done: running `npm run web` in wrapper/test/app copies the assets declared in the package to build/web (after creating the assets with `gaston build`).

I'm just not sure what to do about the bridge since this platform is pure js and doesn't need a bridge. I see 2 options for this

1. The plugins could call `bridge.send` just like they do for other platforms, and that would call a separate js file provided by the plugin instead of sending the call to a native side. In this case, the usage becomes more consistent across platforms.
1. The plugins could avoid calling `bridge.send` and just run the appropriate js without going through the bridge at all. In this case, the builder doesn't need to add the bridge in the code and send `ready` events or anything like that.

@ninjatux @marcusbesjes I was hoping one of you could help me figure this out. I'm currently leaning towards solution #2, but I'm not 100% convinced

**Comment by ninjatux** [comment]
i see the bridge as an utility used internally for allowing bidirectional communication with native platforms. In this case since there is no native platform I don't see why we can't remove the bridge. 
Consistency is done by the implementation code which uses our core libraries.

I would say let's go with solution 2!

**Comment by shawninder** [comment]
```
var bridge = require('vigour-wrapper/lib/bridge')
bridge.on('resume', ...)
```

**Comment by shawninder** [comment]
wrapper is pretty much obsolete
