### ISSUE TITLE
[Events] How should we handle `ready` events

### ISSUE THREAD

**Issue by shawninder** [vigour-io/wrapper#79]
If we can guarantee that the native side is ready before the js starts execution, we don't need this. But We don't want to delay app start to wait for the purchasing plugin to initialize, for example, so I'm expecting this to be a thing.

Every plugin can have it's own `ready` event. + 1 `ready` event for the bridge itself.

For this the js bridge could provide and listen to `window.vigour.native.ready`, which can be called either with `ready(err, data, pluginId)` or `ready(err, data)`.

@jimdebeer @avdwerff @michielibiza : Thoughts? :+1: :-1:?

**Comment by ninjatux** [comment]
for native plugins the startup is made when the js side call the `init` method. this should trigger the setup of the plugin and once done call bridge.ready when finished. if the plugin is already available it can emit `ready` immediately. on the js side we can listen for the `ready` event and take action.

**Comment by shawninder** [comment]
This doesn't correspond with the original intent of the `ready` event, which meant "you can now call this native plugin". In other words, if you call the `init` method, it will be queued by the bridge until the plugin is ready to receive it (which it tells the bridge via the `ready` event)

**Comment by marcusbesjes** [comment]
We should separate "bridgeReady" from "ready", so 

- `bridgeReady`: "ready to receive method calls from the bridge"
  - bridge emits this on plugin when bridge.ready is called
- `ready`: "done initialising, ready for use by user"
  - plugin emits this itself at some point, probably in `init` callback

@shawninder @ninjatux agreed?

**Comment by michielibiza** [comment]
this already exists: 
- ready event without plugin name means bridge is ready
- ready event with plugin name means plugin is ready

**Comment by marcusbesjes** [comment]
ok three levels:
- bridge is ready
- native bridge plugin is ready to receive method calls over the bridge
- plugin is fully initialised, ready to act on all method calls

flow example:

- bridge ready (event 1)
- native `pay` plugin ready to receive calls (event 2)
- `initialise` the plugin by validating the product id's after `region` is established
- all products are recognised and have a price plugin.ready.val = true (event 3)
- we can now start purchasing products

In some cases, there will be no `initialise` step needed, but thats why I proposed to have these events in all cases, and just chained together by default, so that we can "insert" an init step when needed

**Comment by shawninder** [comment]
sure

**Comment by marcusbesjes** [comment]
final implementation fires ready on the plugin by default, if a plugin needs to have additional init steps, it should place a condition on ready.
